# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.api.matrix_files_api import MatrixFilesApi


class TestMatrixFilesApi(unittest.TestCase):
    """MatrixFilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MatrixFilesApi()

    def tearDown(self) -> None:
        pass

    def test_matrix_files(self) -> None:
        """Test case for matrix_files

        List items in the MatrixFile collection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
