# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.api.configuration_files_api import ConfigurationFilesApi


class TestConfigurationFilesApi(unittest.TestCase):
    """ConfigurationFilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigurationFilesApi()

    def tearDown(self) -> None:
        pass

    def test_configuration_files(self) -> None:
        """Test case for configuration_files

        List items in the ConfigurationFile collection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
