# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.api.open_reading_frames_api import OpenReadingFramesApi


class TestOpenReadingFramesApi(unittest.TestCase):
    """OpenReadingFramesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenReadingFramesApi()

    def tearDown(self) -> None:
        pass

    def test_open_reading_frames(self) -> None:
        """Test case for open_reading_frames

        List items in the OpenReadingFrame collection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
