# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.api.access_keys_api import AccessKeysApi


class TestAccessKeysApi(unittest.TestCase):
    """AccessKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessKeysApi()

    def tearDown(self) -> None:
        pass

    def test_access_keys(self) -> None:
        """Test case for access_keys

        List items in the AccessKey collection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
