# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RelatedDonor")

model_instance <- RelatedDonor$new()

test_that("donor", {
  # tests for the property `donor` (character)
  # An identifier for the related donor.

  # uncomment below to test the property
  #expect_equal(model.instance$`donor`, "EXPECTED_RESULT")
})

test_that("relationship_type", {
  # tests for the property `relationship_type` (character)
  # A descriptive term for the related donor’s relationship to this donor.

  # uncomment below to test the property
  #expect_equal(model.instance$`relationship_type`, "EXPECTED_RESULT")
})
