/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GeneLocation1 from './GeneLocation1';

/**
 * The Gene model module.
 * @module model/Gene
 * @version 0.1.0
 */
class Gene {
    /**
     * Constructs a new <code>Gene</code>.
     * A gene in the human or mouse genomes. The genes objects in IGVF are imported from GENCODE.
     * @alias module:model/Gene
     */
    constructor() { 
        
        Gene.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Gene</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Gene} obj Optional instance to populate.
     * @return {module:model/Gene} The populated <code>Gene</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Gene();

            if (data.hasOwnProperty('release_timestamp')) {
                obj['release_timestamp'] = ApiClient.convertToType(data['release_timestamp'], 'String');
            }
            if (data.hasOwnProperty('transcriptome_annotation')) {
                obj['transcriptome_annotation'] = ApiClient.convertToType(data['transcriptome_annotation'], 'String');
            }
            if (data.hasOwnProperty('taxa')) {
                obj['taxa'] = ApiClient.convertToType(data['taxa'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('aliases')) {
                obj['aliases'] = ApiClient.convertToType(data['aliases'], ['String']);
            }
            if (data.hasOwnProperty('creation_timestamp')) {
                obj['creation_timestamp'] = ApiClient.convertToType(data['creation_timestamp'], 'String');
            }
            if (data.hasOwnProperty('submitted_by')) {
                obj['submitted_by'] = ApiClient.convertToType(data['submitted_by'], 'String');
            }
            if (data.hasOwnProperty('submitter_comment')) {
                obj['submitter_comment'] = ApiClient.convertToType(data['submitter_comment'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('geneid')) {
                obj['geneid'] = ApiClient.convertToType(data['geneid'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('synonyms')) {
                obj['synonyms'] = ApiClient.convertToType(data['synonyms'], ['String']);
            }
            if (data.hasOwnProperty('dbxrefs')) {
                obj['dbxrefs'] = ApiClient.convertToType(data['dbxrefs'], ['String']);
            }
            if (data.hasOwnProperty('locations')) {
                obj['locations'] = ApiClient.convertToType(data['locations'], [GeneLocation1]);
            }
            if (data.hasOwnProperty('version_number')) {
                obj['version_number'] = ApiClient.convertToType(data['version_number'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], ['String']);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('geneid_with_version')) {
                obj['geneid_with_version'] = ApiClient.convertToType(data['geneid_with_version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Gene</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Gene</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['release_timestamp'] && !(typeof data['release_timestamp'] === 'string' || data['release_timestamp'] instanceof String)) {
            throw new Error("Expected the field `release_timestamp` to be a primitive type in the JSON string but got " + data['release_timestamp']);
        }
        // ensure the json data is a string
        if (data['transcriptome_annotation'] && !(typeof data['transcriptome_annotation'] === 'string' || data['transcriptome_annotation'] instanceof String)) {
            throw new Error("Expected the field `transcriptome_annotation` to be a primitive type in the JSON string but got " + data['transcriptome_annotation']);
        }
        // ensure the json data is a string
        if (data['taxa'] && !(typeof data['taxa'] === 'string' || data['taxa'] instanceof String)) {
            throw new Error("Expected the field `taxa` to be a primitive type in the JSON string but got " + data['taxa']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['schema_version'] && !(typeof data['schema_version'] === 'string' || data['schema_version'] instanceof String)) {
            throw new Error("Expected the field `schema_version` to be a primitive type in the JSON string but got " + data['schema_version']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['aliases'])) {
            throw new Error("Expected the field `aliases` to be an array in the JSON data but got " + data['aliases']);
        }
        // ensure the json data is a string
        if (data['creation_timestamp'] && !(typeof data['creation_timestamp'] === 'string' || data['creation_timestamp'] instanceof String)) {
            throw new Error("Expected the field `creation_timestamp` to be a primitive type in the JSON string but got " + data['creation_timestamp']);
        }
        // ensure the json data is a string
        if (data['submitted_by'] && !(typeof data['submitted_by'] === 'string' || data['submitted_by'] instanceof String)) {
            throw new Error("Expected the field `submitted_by` to be a primitive type in the JSON string but got " + data['submitted_by']);
        }
        // ensure the json data is a string
        if (data['submitter_comment'] && !(typeof data['submitter_comment'] === 'string' || data['submitter_comment'] instanceof String)) {
            throw new Error("Expected the field `submitter_comment` to be a primitive type in the JSON string but got " + data['submitter_comment']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['geneid'] && !(typeof data['geneid'] === 'string' || data['geneid'] instanceof String)) {
            throw new Error("Expected the field `geneid` to be a primitive type in the JSON string but got " + data['geneid']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['synonyms'])) {
            throw new Error("Expected the field `synonyms` to be an array in the JSON data but got " + data['synonyms']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dbxrefs'])) {
            throw new Error("Expected the field `dbxrefs` to be an array in the JSON data but got " + data['dbxrefs']);
        }
        if (data['locations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['locations'])) {
                throw new Error("Expected the field `locations` to be an array in the JSON data but got " + data['locations']);
            }
            // validate the optional field `locations` (array)
            for (const item of data['locations']) {
                GeneLocation1.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['version_number'] && !(typeof data['version_number'] === 'string' || data['version_number'] instanceof String)) {
            throw new Error("Expected the field `version_number` to be a primitive type in the JSON string but got " + data['version_number']);
        }
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['@type'])) {
            throw new Error("Expected the field `@type` to be an array in the JSON data but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['geneid_with_version'] && !(typeof data['geneid_with_version'] === 'string' || data['geneid_with_version'] instanceof String)) {
            throw new Error("Expected the field `geneid_with_version` to be a primitive type in the JSON string but got " + data['geneid_with_version']);
        }

        return true;
    }


}



/**
 * The date the object was released.
 * @member {String} release_timestamp
 */
Gene.prototype['release_timestamp'] = undefined;

/**
 * The annotation and version of the reference resource.
 * @member {module:model/Gene.TranscriptomeAnnotationEnum} transcriptome_annotation
 */
Gene.prototype['transcriptome_annotation'] = undefined;

/**
 * The species of the organism.
 * @member {module:model/Gene.TaxaEnum} taxa
 */
Gene.prototype['taxa'] = undefined;

/**
 * The status of the metadata object.
 * @member {module:model/Gene.StatusEnum} status
 */
Gene.prototype['status'] = undefined;

/**
 * The version of the JSON schema that the server uses to validate the object.
 * @member {String} schema_version
 */
Gene.prototype['schema_version'] = undefined;

/**
 * The unique identifier associated with every object.
 * @member {String} uuid
 */
Gene.prototype['uuid'] = undefined;

/**
 * DACC internal notes.
 * @member {String} notes
 */
Gene.prototype['notes'] = undefined;

/**
 * Lab specific identifiers to reference an object.
 * @member {Array.<String>} aliases
 */
Gene.prototype['aliases'] = undefined;

/**
 * The date the object was created.
 * @member {String} creation_timestamp
 */
Gene.prototype['creation_timestamp'] = undefined;

/**
 * The user who submitted the object.
 * @member {String} submitted_by
 */
Gene.prototype['submitted_by'] = undefined;

/**
 * Additional information specified by the submitter to be displayed as a comment on the portal.
 * @member {String} submitter_comment
 */
Gene.prototype['submitter_comment'] = undefined;

/**
 * A plain text description of the object.
 * @member {String} description
 */
Gene.prototype['description'] = undefined;

/**
 * ENSEMBL GeneID of official nomenclature approved gene. The GeneID does not include the current version number suffix.
 * @member {String} geneid
 */
Gene.prototype['geneid'] = undefined;

/**
 * Gene symbol approved by the official nomenclature.
 * @member {String} symbol
 */
Gene.prototype['symbol'] = undefined;

/**
 * The full gene name preferably approved by the official nomenclature.
 * @member {String} name
 */
Gene.prototype['name'] = undefined;

/**
 * Alternative symbols that have been used to refer to the gene.
 * @member {Array.<String>} synonyms
 */
Gene.prototype['synonyms'] = undefined;

/**
 * Unique identifiers from external resources.
 * @member {Array.<String>} dbxrefs
 */
Gene.prototype['dbxrefs'] = undefined;

/**
 * Gene locations specified using 1-based, closed coordinates for different versions of reference genome assemblies.
 * @member {Array.<module:model/GeneLocation1>} locations
 */
Gene.prototype['locations'] = undefined;

/**
 * Current ENSEMBL GeneID version number of the gene.
 * @member {String} version_number
 */
Gene.prototype['version_number'] = undefined;

/**
 * @member {String} @id
 */
Gene.prototype['@id'] = undefined;

/**
 * @member {Array.<String>} @type
 */
Gene.prototype['@type'] = undefined;

/**
 * A summary of the object.
 * @member {String} summary
 */
Gene.prototype['summary'] = undefined;

/**
 * @member {String} title
 */
Gene.prototype['title'] = undefined;

/**
 * The ENSEMBL GeneID concatenated with its version number.
 * @member {String} geneid_with_version
 */
Gene.prototype['geneid_with_version'] = undefined;





/**
 * Allowed values for the <code>transcriptome_annotation</code> property.
 * @enum {String}
 * @readonly
 */
Gene['TranscriptomeAnnotationEnum'] = {

    /**
     * value: "GENCODE 40"
     * @const
     */
    "40": "GENCODE 40",

    /**
     * value: "GENCODE 41"
     * @const
     */
    "41": "GENCODE 41",

    /**
     * value: "GENCODE 42"
     * @const
     */
    "42": "GENCODE 42",

    /**
     * value: "GENCODE 43"
     * @const
     */
    "43": "GENCODE 43",

    /**
     * value: "GENCODE 44"
     * @const
     */
    "44": "GENCODE 44",

    /**
     * value: "GENCODE 45"
     * @const
     */
    "45": "GENCODE 45",

    /**
     * value: "GENCODE M30"
     * @const
     */
    "M30": "GENCODE M30",

    /**
     * value: "GENCODE M31"
     * @const
     */
    "M31": "GENCODE M31",

    /**
     * value: "GENCODE M32"
     * @const
     */
    "M32": "GENCODE M32",

    /**
     * value: "GENCODE M33"
     * @const
     */
    "M33": "GENCODE M33",

    /**
     * value: "GENCODE M34"
     * @const
     */
    "M34": "GENCODE M34"
};


/**
 * Allowed values for the <code>taxa</code> property.
 * @enum {String}
 * @readonly
 */
Gene['TaxaEnum'] = {

    /**
     * value: "Homo sapiens"
     * @const
     */
    "Homo sapiens": "Homo sapiens",

    /**
     * value: "Mus musculus"
     * @const
     */
    "Mus musculus": "Mus musculus"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Gene['StatusEnum'] = {

    /**
     * value: "archived"
     * @const
     */
    "archived": "archived",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "in progress"
     * @const
     */
    "in progress": "in progress",

    /**
     * value: "released"
     * @const
     */
    "released": "released"
};



export default Gene;

