/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tissue model module.
 * @module model/Tissue
 * @version 0.1.0
 */
class Tissue {
    /**
     * Constructs a new <code>Tissue</code>.
     * A biosample that is directly harvested from a donor, typically a dissection from an organ.
     * @alias module:model/Tissue
     */
    constructor() { 
        
        Tissue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tissue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tissue} obj Optional instance to populate.
     * @return {module:model/Tissue} The populated <code>Tissue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tissue();

            if (data.hasOwnProperty('release_timestamp')) {
                obj['release_timestamp'] = ApiClient.convertToType(data['release_timestamp'], 'String');
            }
            if (data.hasOwnProperty('publications')) {
                obj['publications'] = ApiClient.convertToType(data['publications'], ['String']);
            }
            if (data.hasOwnProperty('publication_identifiers')) {
                obj['publication_identifiers'] = ApiClient.convertToType(data['publication_identifiers'], ['String']);
            }
            if (data.hasOwnProperty('taxa')) {
                obj['taxa'] = ApiClient.convertToType(data['taxa'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], ['String']);
            }
            if (data.hasOwnProperty('lot_id')) {
                obj['lot_id'] = ApiClient.convertToType(data['lot_id'], 'String');
            }
            if (data.hasOwnProperty('product_id')) {
                obj['product_id'] = ApiClient.convertToType(data['product_id'], 'String');
            }
            if (data.hasOwnProperty('documents')) {
                obj['documents'] = ApiClient.convertToType(data['documents'], ['String']);
            }
            if (data.hasOwnProperty('lab')) {
                obj['lab'] = ApiClient.convertToType(data['lab'], 'String');
            }
            if (data.hasOwnProperty('award')) {
                obj['award'] = ApiClient.convertToType(data['award'], 'String');
            }
            if (data.hasOwnProperty('accession')) {
                obj['accession'] = ApiClient.convertToType(data['accession'], 'String');
            }
            if (data.hasOwnProperty('alternate_accessions')) {
                obj['alternate_accessions'] = ApiClient.convertToType(data['alternate_accessions'], ['String']);
            }
            if (data.hasOwnProperty('collections')) {
                obj['collections'] = ApiClient.convertToType(data['collections'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('revoke_detail')) {
                obj['revoke_detail'] = ApiClient.convertToType(data['revoke_detail'], 'String');
            }
            if (data.hasOwnProperty('schema_version')) {
                obj['schema_version'] = ApiClient.convertToType(data['schema_version'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('aliases')) {
                obj['aliases'] = ApiClient.convertToType(data['aliases'], ['String']);
            }
            if (data.hasOwnProperty('creation_timestamp')) {
                obj['creation_timestamp'] = ApiClient.convertToType(data['creation_timestamp'], 'String');
            }
            if (data.hasOwnProperty('submitted_by')) {
                obj['submitted_by'] = ApiClient.convertToType(data['submitted_by'], 'String');
            }
            if (data.hasOwnProperty('submitter_comment')) {
                obj['submitter_comment'] = ApiClient.convertToType(data['submitter_comment'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('lower_bound_age')) {
                obj['lower_bound_age'] = ApiClient.convertToType(data['lower_bound_age'], 'Number');
            }
            if (data.hasOwnProperty('upper_bound_age')) {
                obj['upper_bound_age'] = ApiClient.convertToType(data['upper_bound_age'], 'Number');
            }
            if (data.hasOwnProperty('age_units')) {
                obj['age_units'] = ApiClient.convertToType(data['age_units'], 'String');
            }
            if (data.hasOwnProperty('sample_terms')) {
                obj['sample_terms'] = ApiClient.convertToType(data['sample_terms'], ['String']);
            }
            if (data.hasOwnProperty('disease_terms')) {
                obj['disease_terms'] = ApiClient.convertToType(data['disease_terms'], ['String']);
            }
            if (data.hasOwnProperty('pooled_from')) {
                obj['pooled_from'] = ApiClient.convertToType(data['pooled_from'], ['String']);
            }
            if (data.hasOwnProperty('part_of')) {
                obj['part_of'] = ApiClient.convertToType(data['part_of'], 'String');
            }
            if (data.hasOwnProperty('originated_from')) {
                obj['originated_from'] = ApiClient.convertToType(data['originated_from'], 'String');
            }
            if (data.hasOwnProperty('treatments')) {
                obj['treatments'] = ApiClient.convertToType(data['treatments'], ['String']);
            }
            if (data.hasOwnProperty('donors')) {
                obj['donors'] = ApiClient.convertToType(data['donors'], ['String']);
            }
            if (data.hasOwnProperty('biomarkers')) {
                obj['biomarkers'] = ApiClient.convertToType(data['biomarkers'], ['String']);
            }
            if (data.hasOwnProperty('embryonic')) {
                obj['embryonic'] = ApiClient.convertToType(data['embryonic'], 'Boolean');
            }
            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = ApiClient.convertToType(data['modifications'], ['String']);
            }
            if (data.hasOwnProperty('cellular_sub_pool')) {
                obj['cellular_sub_pool'] = ApiClient.convertToType(data['cellular_sub_pool'], 'String');
            }
            if (data.hasOwnProperty('starting_amount')) {
                obj['starting_amount'] = ApiClient.convertToType(data['starting_amount'], 'Number');
            }
            if (data.hasOwnProperty('starting_amount_units')) {
                obj['starting_amount_units'] = ApiClient.convertToType(data['starting_amount_units'], 'String');
            }
            if (data.hasOwnProperty('dbxrefs')) {
                obj['dbxrefs'] = ApiClient.convertToType(data['dbxrefs'], ['String']);
            }
            if (data.hasOwnProperty('date_obtained')) {
                obj['date_obtained'] = ApiClient.convertToType(data['date_obtained'], 'String');
            }
            if (data.hasOwnProperty('sorted_from')) {
                obj['sorted_from'] = ApiClient.convertToType(data['sorted_from'], 'String');
            }
            if (data.hasOwnProperty('sorted_from_detail')) {
                obj['sorted_from_detail'] = ApiClient.convertToType(data['sorted_from_detail'], 'String');
            }
            if (data.hasOwnProperty('virtual')) {
                obj['virtual'] = ApiClient.convertToType(data['virtual'], 'Boolean');
            }
            if (data.hasOwnProperty('construct_library_sets')) {
                obj['construct_library_sets'] = ApiClient.convertToType(data['construct_library_sets'], ['String']);
            }
            if (data.hasOwnProperty('moi')) {
                obj['moi'] = ApiClient.convertToType(data['moi'], 'Number');
            }
            if (data.hasOwnProperty('nucleic_acid_delivery')) {
                obj['nucleic_acid_delivery'] = ApiClient.convertToType(data['nucleic_acid_delivery'], 'String');
            }
            if (data.hasOwnProperty('time_post_library_delivery')) {
                obj['time_post_library_delivery'] = ApiClient.convertToType(data['time_post_library_delivery'], 'Number');
            }
            if (data.hasOwnProperty('time_post_library_delivery_units')) {
                obj['time_post_library_delivery_units'] = ApiClient.convertToType(data['time_post_library_delivery_units'], 'String');
            }
            if (data.hasOwnProperty('protocols')) {
                obj['protocols'] = ApiClient.convertToType(data['protocols'], ['String']);
            }
            if (data.hasOwnProperty('pmi')) {
                obj['pmi'] = ApiClient.convertToType(data['pmi'], 'Number');
            }
            if (data.hasOwnProperty('pmi_units')) {
                obj['pmi_units'] = ApiClient.convertToType(data['pmi_units'], 'String');
            }
            if (data.hasOwnProperty('ccf_id')) {
                obj['ccf_id'] = ApiClient.convertToType(data['ccf_id'], 'String');
            }
            if (data.hasOwnProperty('preservation_method')) {
                obj['preservation_method'] = ApiClient.convertToType(data['preservation_method'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], ['String']);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('file_sets')) {
                obj['file_sets'] = ApiClient.convertToType(data['file_sets'], ['String']);
            }
            if (data.hasOwnProperty('multiplexed_in')) {
                obj['multiplexed_in'] = ApiClient.convertToType(data['multiplexed_in'], ['String']);
            }
            if (data.hasOwnProperty('sorted_fractions')) {
                obj['sorted_fractions'] = ApiClient.convertToType(data['sorted_fractions'], ['String']);
            }
            if (data.hasOwnProperty('origin_of')) {
                obj['origin_of'] = ApiClient.convertToType(data['origin_of'], ['String']);
            }
            if (data.hasOwnProperty('institutional_certificates')) {
                obj['institutional_certificates'] = ApiClient.convertToType(data['institutional_certificates'], ['String']);
            }
            if (data.hasOwnProperty('sex')) {
                obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
            }
            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'String');
            }
            if (data.hasOwnProperty('upper_bound_age_in_hours')) {
                obj['upper_bound_age_in_hours'] = ApiClient.convertToType(data['upper_bound_age_in_hours'], 'Number');
            }
            if (data.hasOwnProperty('lower_bound_age_in_hours')) {
                obj['lower_bound_age_in_hours'] = ApiClient.convertToType(data['lower_bound_age_in_hours'], 'Number');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], ['String']);
            }
            if (data.hasOwnProperty('pooled_in')) {
                obj['pooled_in'] = ApiClient.convertToType(data['pooled_in'], ['String']);
            }
            if (data.hasOwnProperty('classifications')) {
                obj['classifications'] = ApiClient.convertToType(data['classifications'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Tissue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Tissue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['release_timestamp'] && !(typeof data['release_timestamp'] === 'string' || data['release_timestamp'] instanceof String)) {
            throw new Error("Expected the field `release_timestamp` to be a primitive type in the JSON string but got " + data['release_timestamp']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['publications'])) {
            throw new Error("Expected the field `publications` to be an array in the JSON data but got " + data['publications']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['publication_identifiers'])) {
            throw new Error("Expected the field `publication_identifiers` to be an array in the JSON data but got " + data['publication_identifiers']);
        }
        // ensure the json data is a string
        if (data['taxa'] && !(typeof data['taxa'] === 'string' || data['taxa'] instanceof String)) {
            throw new Error("Expected the field `taxa` to be a primitive type in the JSON string but got " + data['taxa']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['sources'])) {
            throw new Error("Expected the field `sources` to be an array in the JSON data but got " + data['sources']);
        }
        // ensure the json data is a string
        if (data['lot_id'] && !(typeof data['lot_id'] === 'string' || data['lot_id'] instanceof String)) {
            throw new Error("Expected the field `lot_id` to be a primitive type in the JSON string but got " + data['lot_id']);
        }
        // ensure the json data is a string
        if (data['product_id'] && !(typeof data['product_id'] === 'string' || data['product_id'] instanceof String)) {
            throw new Error("Expected the field `product_id` to be a primitive type in the JSON string but got " + data['product_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['documents'])) {
            throw new Error("Expected the field `documents` to be an array in the JSON data but got " + data['documents']);
        }
        // ensure the json data is a string
        if (data['lab'] && !(typeof data['lab'] === 'string' || data['lab'] instanceof String)) {
            throw new Error("Expected the field `lab` to be a primitive type in the JSON string but got " + data['lab']);
        }
        // ensure the json data is a string
        if (data['award'] && !(typeof data['award'] === 'string' || data['award'] instanceof String)) {
            throw new Error("Expected the field `award` to be a primitive type in the JSON string but got " + data['award']);
        }
        // ensure the json data is a string
        if (data['accession'] && !(typeof data['accession'] === 'string' || data['accession'] instanceof String)) {
            throw new Error("Expected the field `accession` to be a primitive type in the JSON string but got " + data['accession']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['alternate_accessions'])) {
            throw new Error("Expected the field `alternate_accessions` to be an array in the JSON data but got " + data['alternate_accessions']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['collections'])) {
            throw new Error("Expected the field `collections` to be an array in the JSON data but got " + data['collections']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['revoke_detail'] && !(typeof data['revoke_detail'] === 'string' || data['revoke_detail'] instanceof String)) {
            throw new Error("Expected the field `revoke_detail` to be a primitive type in the JSON string but got " + data['revoke_detail']);
        }
        // ensure the json data is a string
        if (data['schema_version'] && !(typeof data['schema_version'] === 'string' || data['schema_version'] instanceof String)) {
            throw new Error("Expected the field `schema_version` to be a primitive type in the JSON string but got " + data['schema_version']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['aliases'])) {
            throw new Error("Expected the field `aliases` to be an array in the JSON data but got " + data['aliases']);
        }
        // ensure the json data is a string
        if (data['creation_timestamp'] && !(typeof data['creation_timestamp'] === 'string' || data['creation_timestamp'] instanceof String)) {
            throw new Error("Expected the field `creation_timestamp` to be a primitive type in the JSON string but got " + data['creation_timestamp']);
        }
        // ensure the json data is a string
        if (data['submitted_by'] && !(typeof data['submitted_by'] === 'string' || data['submitted_by'] instanceof String)) {
            throw new Error("Expected the field `submitted_by` to be a primitive type in the JSON string but got " + data['submitted_by']);
        }
        // ensure the json data is a string
        if (data['submitter_comment'] && !(typeof data['submitter_comment'] === 'string' || data['submitter_comment'] instanceof String)) {
            throw new Error("Expected the field `submitter_comment` to be a primitive type in the JSON string but got " + data['submitter_comment']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['age_units'] && !(typeof data['age_units'] === 'string' || data['age_units'] instanceof String)) {
            throw new Error("Expected the field `age_units` to be a primitive type in the JSON string but got " + data['age_units']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['sample_terms'])) {
            throw new Error("Expected the field `sample_terms` to be an array in the JSON data but got " + data['sample_terms']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['disease_terms'])) {
            throw new Error("Expected the field `disease_terms` to be an array in the JSON data but got " + data['disease_terms']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['pooled_from'])) {
            throw new Error("Expected the field `pooled_from` to be an array in the JSON data but got " + data['pooled_from']);
        }
        // ensure the json data is a string
        if (data['part_of'] && !(typeof data['part_of'] === 'string' || data['part_of'] instanceof String)) {
            throw new Error("Expected the field `part_of` to be a primitive type in the JSON string but got " + data['part_of']);
        }
        // ensure the json data is a string
        if (data['originated_from'] && !(typeof data['originated_from'] === 'string' || data['originated_from'] instanceof String)) {
            throw new Error("Expected the field `originated_from` to be a primitive type in the JSON string but got " + data['originated_from']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['treatments'])) {
            throw new Error("Expected the field `treatments` to be an array in the JSON data but got " + data['treatments']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['donors'])) {
            throw new Error("Expected the field `donors` to be an array in the JSON data but got " + data['donors']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['biomarkers'])) {
            throw new Error("Expected the field `biomarkers` to be an array in the JSON data but got " + data['biomarkers']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['modifications'])) {
            throw new Error("Expected the field `modifications` to be an array in the JSON data but got " + data['modifications']);
        }
        // ensure the json data is a string
        if (data['cellular_sub_pool'] && !(typeof data['cellular_sub_pool'] === 'string' || data['cellular_sub_pool'] instanceof String)) {
            throw new Error("Expected the field `cellular_sub_pool` to be a primitive type in the JSON string but got " + data['cellular_sub_pool']);
        }
        // ensure the json data is a string
        if (data['starting_amount_units'] && !(typeof data['starting_amount_units'] === 'string' || data['starting_amount_units'] instanceof String)) {
            throw new Error("Expected the field `starting_amount_units` to be a primitive type in the JSON string but got " + data['starting_amount_units']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['dbxrefs'])) {
            throw new Error("Expected the field `dbxrefs` to be an array in the JSON data but got " + data['dbxrefs']);
        }
        // ensure the json data is a string
        if (data['date_obtained'] && !(typeof data['date_obtained'] === 'string' || data['date_obtained'] instanceof String)) {
            throw new Error("Expected the field `date_obtained` to be a primitive type in the JSON string but got " + data['date_obtained']);
        }
        // ensure the json data is a string
        if (data['sorted_from'] && !(typeof data['sorted_from'] === 'string' || data['sorted_from'] instanceof String)) {
            throw new Error("Expected the field `sorted_from` to be a primitive type in the JSON string but got " + data['sorted_from']);
        }
        // ensure the json data is a string
        if (data['sorted_from_detail'] && !(typeof data['sorted_from_detail'] === 'string' || data['sorted_from_detail'] instanceof String)) {
            throw new Error("Expected the field `sorted_from_detail` to be a primitive type in the JSON string but got " + data['sorted_from_detail']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['construct_library_sets'])) {
            throw new Error("Expected the field `construct_library_sets` to be an array in the JSON data but got " + data['construct_library_sets']);
        }
        // ensure the json data is a string
        if (data['nucleic_acid_delivery'] && !(typeof data['nucleic_acid_delivery'] === 'string' || data['nucleic_acid_delivery'] instanceof String)) {
            throw new Error("Expected the field `nucleic_acid_delivery` to be a primitive type in the JSON string but got " + data['nucleic_acid_delivery']);
        }
        // ensure the json data is a string
        if (data['time_post_library_delivery_units'] && !(typeof data['time_post_library_delivery_units'] === 'string' || data['time_post_library_delivery_units'] instanceof String)) {
            throw new Error("Expected the field `time_post_library_delivery_units` to be a primitive type in the JSON string but got " + data['time_post_library_delivery_units']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['protocols'])) {
            throw new Error("Expected the field `protocols` to be an array in the JSON data but got " + data['protocols']);
        }
        // ensure the json data is a string
        if (data['pmi_units'] && !(typeof data['pmi_units'] === 'string' || data['pmi_units'] instanceof String)) {
            throw new Error("Expected the field `pmi_units` to be a primitive type in the JSON string but got " + data['pmi_units']);
        }
        // ensure the json data is a string
        if (data['ccf_id'] && !(typeof data['ccf_id'] === 'string' || data['ccf_id'] instanceof String)) {
            throw new Error("Expected the field `ccf_id` to be a primitive type in the JSON string but got " + data['ccf_id']);
        }
        // ensure the json data is a string
        if (data['preservation_method'] && !(typeof data['preservation_method'] === 'string' || data['preservation_method'] instanceof String)) {
            throw new Error("Expected the field `preservation_method` to be a primitive type in the JSON string but got " + data['preservation_method']);
        }
        // ensure the json data is a string
        if (data['@id'] && !(typeof data['@id'] === 'string' || data['@id'] instanceof String)) {
            throw new Error("Expected the field `@id` to be a primitive type in the JSON string but got " + data['@id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['@type'])) {
            throw new Error("Expected the field `@type` to be an array in the JSON data but got " + data['@type']);
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['file_sets'])) {
            throw new Error("Expected the field `file_sets` to be an array in the JSON data but got " + data['file_sets']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['multiplexed_in'])) {
            throw new Error("Expected the field `multiplexed_in` to be an array in the JSON data but got " + data['multiplexed_in']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['sorted_fractions'])) {
            throw new Error("Expected the field `sorted_fractions` to be an array in the JSON data but got " + data['sorted_fractions']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['origin_of'])) {
            throw new Error("Expected the field `origin_of` to be an array in the JSON data but got " + data['origin_of']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['institutional_certificates'])) {
            throw new Error("Expected the field `institutional_certificates` to be an array in the JSON data but got " + data['institutional_certificates']);
        }
        // ensure the json data is a string
        if (data['sex'] && !(typeof data['sex'] === 'string' || data['sex'] instanceof String)) {
            throw new Error("Expected the field `sex` to be a primitive type in the JSON string but got " + data['sex']);
        }
        // ensure the json data is a string
        if (data['age'] && !(typeof data['age'] === 'string' || data['age'] instanceof String)) {
            throw new Error("Expected the field `age` to be a primitive type in the JSON string but got " + data['age']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['parts'])) {
            throw new Error("Expected the field `parts` to be an array in the JSON data but got " + data['parts']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['pooled_in'])) {
            throw new Error("Expected the field `pooled_in` to be an array in the JSON data but got " + data['pooled_in']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['classifications'])) {
            throw new Error("Expected the field `classifications` to be an array in the JSON data but got " + data['classifications']);
        }

        return true;
    }


}



/**
 * The date the object was released.
 * @member {String} release_timestamp
 */
Tissue.prototype['release_timestamp'] = undefined;

/**
 * The publications associated with this object.
 * @member {Array.<String>} publications
 */
Tissue.prototype['publications'] = undefined;

/**
 * The publication identifiers that provide more information about the object.
 * @member {Array.<String>} publication_identifiers
 */
Tissue.prototype['publication_identifiers'] = undefined;

/**
 * The species of the organism.
 * @member {module:model/Tissue.TaxaEnum} taxa
 */
Tissue.prototype['taxa'] = undefined;

/**
 * An external resource with additional information.
 * @member {String} url
 */
Tissue.prototype['url'] = undefined;

/**
 * The originating lab(s) or vendor(s).
 * @member {Array.<String>} sources
 */
Tissue.prototype['sources'] = undefined;

/**
 * The lot identifier provided by the originating lab or vendor.
 * @member {String} lot_id
 */
Tissue.prototype['lot_id'] = undefined;

/**
 * The product identifier provided by the originating lab or vendor.
 * @member {String} product_id
 */
Tissue.prototype['product_id'] = undefined;

/**
 * Documents that provide additional information (not data file).
 * @member {Array.<String>} documents
 */
Tissue.prototype['documents'] = undefined;

/**
 * Lab associated with the submission.
 * @member {String} lab
 */
Tissue.prototype['lab'] = undefined;

/**
 * Grant associated with the submission.
 * @member {String} award
 */
Tissue.prototype['award'] = undefined;

/**
 * A unique identifier to be used to reference the object prefixed with IGVF.
 * @member {String} accession
 */
Tissue.prototype['accession'] = undefined;

/**
 * Accessions previously assigned to objects that have been merged with this object.
 * @member {Array.<String>} alternate_accessions
 */
Tissue.prototype['alternate_accessions'] = undefined;

/**
 * Some samples are part of particular data collections.
 * @member {Array.<module:model/Tissue.CollectionsEnum>} collections
 */
Tissue.prototype['collections'] = undefined;

/**
 * The status of the metadata object.
 * @member {module:model/Tissue.StatusEnum} status
 */
Tissue.prototype['status'] = undefined;

/**
 * Explanation of why an object was transitioned to the revoked status.
 * @member {String} revoke_detail
 */
Tissue.prototype['revoke_detail'] = undefined;

/**
 * The version of the JSON schema that the server uses to validate the object.
 * @member {String} schema_version
 */
Tissue.prototype['schema_version'] = undefined;

/**
 * The unique identifier associated with every object.
 * @member {String} uuid
 */
Tissue.prototype['uuid'] = undefined;

/**
 * DACC internal notes.
 * @member {String} notes
 */
Tissue.prototype['notes'] = undefined;

/**
 * Lab specific identifiers to reference an object.
 * @member {Array.<String>} aliases
 */
Tissue.prototype['aliases'] = undefined;

/**
 * The date the object was created.
 * @member {String} creation_timestamp
 */
Tissue.prototype['creation_timestamp'] = undefined;

/**
 * The user who submitted the object.
 * @member {String} submitted_by
 */
Tissue.prototype['submitted_by'] = undefined;

/**
 * Additional information specified by the submitter to be displayed as a comment on the portal.
 * @member {String} submitter_comment
 */
Tissue.prototype['submitter_comment'] = undefined;

/**
 * A plain text description of the object.
 * @member {String} description
 */
Tissue.prototype['description'] = undefined;

/**
 * Lower bound of age of the organism at the time of collection of the sample.
 * @member {Number} lower_bound_age
 */
Tissue.prototype['lower_bound_age'] = undefined;

/**
 * Upper bound of age of the organism at the time of collection of the sample.
 * @member {Number} upper_bound_age
 */
Tissue.prototype['upper_bound_age'] = undefined;

/**
 * The units of time associated with age of the biosample.
 * @member {module:model/Tissue.AgeUnitsEnum} age_units
 */
Tissue.prototype['age_units'] = undefined;

/**
 * Ontology terms identifying a biosample.
 * @member {Array.<String>} sample_terms
 */
Tissue.prototype['sample_terms'] = undefined;

/**
 * Ontology term of the disease associated with the biosample.
 * @member {Array.<String>} disease_terms
 */
Tissue.prototype['disease_terms'] = undefined;

/**
 * The biosamples this biosample is pooled from.
 * @member {Array.<String>} pooled_from
 */
Tissue.prototype['pooled_from'] = undefined;

/**
 * Links to a biosample which represents a larger sample from which this sample was taken regardless of whether it is a tissue taken from an organism or smaller slices of a piece of tissue or aliquots of a cell growth.
 * @member {String} part_of
 */
Tissue.prototype['part_of'] = undefined;

/**
 * Links to a biosample that was originated from due to differentiation, dedifferentiation, reprogramming, or the introduction of a genetic modification.
 * @member {String} originated_from
 */
Tissue.prototype['originated_from'] = undefined;

/**
 * A list of treatments applied to the biosample with the purpose of perturbation.
 * @member {Array.<String>} treatments
 */
Tissue.prototype['treatments'] = undefined;

/**
 * Donor(s) the sample was derived from.
 * @member {Array.<String>} donors
 */
Tissue.prototype['donors'] = undefined;

/**
 * Biological markers that are associated with this sample.
 * @member {Array.<String>} biomarkers
 */
Tissue.prototype['biomarkers'] = undefined;

/**
 * Biosample is embryonic.
 * @member {Boolean} embryonic
 */
Tissue.prototype['embryonic'] = undefined;

/**
 * Links to modifications applied to this biosample.
 * @member {Array.<String>} modifications
 */
Tissue.prototype['modifications'] = undefined;

/**
 * Cellular sub-pool fraction of the sample. Also known as PKR and sub-library.
 * @member {String} cellular_sub_pool
 */
Tissue.prototype['cellular_sub_pool'] = undefined;

/**
 * The initial quantity of samples obtained.
 * @member {Number} starting_amount
 */
Tissue.prototype['starting_amount'] = undefined;

/**
 * The units used to quantify the amount of samples obtained.
 * @member {module:model/Tissue.StartingAmountUnitsEnum} starting_amount_units
 */
Tissue.prototype['starting_amount_units'] = undefined;

/**
 * Biosample identifiers from external resources, such as Biosample database or Cellosaurus.
 * @member {Array.<String>} dbxrefs
 */
Tissue.prototype['dbxrefs'] = undefined;

/**
 * The date the sample was harvested, dissected or created, depending on the type of the sample.
 * @member {String} date_obtained
 */
Tissue.prototype['date_obtained'] = undefined;

/**
 * Links to a larger sample from which this sample was obtained through sorting.
 * @member {String} sorted_from
 */
Tissue.prototype['sorted_from'] = undefined;

/**
 * Detail for sample sorted into fractions capturing information about sorting.
 * @member {String} sorted_from_detail
 */
Tissue.prototype['sorted_from_detail'] = undefined;

/**
 * Virtual samples are not representing actual physical entities from experiments, but rather capturing metadata about hypothetical samples that the reported analysis results are relevant for.
 * @member {Boolean} virtual
 */
Tissue.prototype['virtual'] = undefined;

/**
 * The construct library sets of vectors introduced to this sample prior to performing an assay.
 * @member {Array.<String>} construct_library_sets
 */
Tissue.prototype['construct_library_sets'] = undefined;

/**
 * The actual multiplicity of infection (MOI) for vectors introduced to this sample. At least one construct library set must be specified in order to specify MOI. This property should capture the actual MOI, and not the targeted MOI.
 * @member {Number} moi
 */
Tissue.prototype['moi'] = undefined;

/**
 * Method of introduction of nucleic acid into the cell.
 * @member {module:model/Tissue.NucleicAcidDeliveryEnum} nucleic_acid_delivery
 */
Tissue.prototype['nucleic_acid_delivery'] = undefined;

/**
 * The time that elapsed past the time-point when the construct library sets were introduced.
 * @member {Number} time_post_library_delivery
 */
Tissue.prototype['time_post_library_delivery'] = undefined;

/**
 * The units of time that elapsed past the point when the construct library sets were introduced.
 * @member {module:model/Tissue.TimePostLibraryDeliveryUnitsEnum} time_post_library_delivery_units
 */
Tissue.prototype['time_post_library_delivery_units'] = undefined;

/**
 * Links to the protocol(s) for preparing the samples on Protocols.io.
 * @member {Array.<String>} protocols
 */
Tissue.prototype['protocols'] = undefined;

/**
 * The amount of time elapsed since death.
 * @member {Number} pmi
 */
Tissue.prototype['pmi'] = undefined;

/**
 * The unit in which the PMI time was reported.
 * @member {module:model/Tissue.PmiUnitsEnum} pmi_units
 */
Tissue.prototype['pmi_units'] = undefined;

/**
 * HubMap Common Coordinate Framework unique identifier corresponding to the organ, biological structure, and spatial location of the tissue specimen.
 * @member {String} ccf_id
 */
Tissue.prototype['ccf_id'] = undefined;

/**
 * The method by which the tissue was preserved: cryopreservation (slow-freeze) or flash-freezing.
 * @member {module:model/Tissue.PreservationMethodEnum} preservation_method
 */
Tissue.prototype['preservation_method'] = undefined;

/**
 * @member {String} @id
 */
Tissue.prototype['@id'] = undefined;

/**
 * @member {Array.<String>} @type
 */
Tissue.prototype['@type'] = undefined;

/**
 * A summary of the sample.
 * @member {String} summary
 */
Tissue.prototype['summary'] = undefined;

/**
 * The file sets linked to this sample.
 * @member {Array.<String>} file_sets
 */
Tissue.prototype['file_sets'] = undefined;

/**
 * The multiplexed samples in which this sample is included.
 * @member {Array.<String>} multiplexed_in
 */
Tissue.prototype['multiplexed_in'] = undefined;

/**
 * The fractions into which this sample has been sorted.
 * @member {Array.<String>} sorted_fractions
 */
Tissue.prototype['sorted_fractions'] = undefined;

/**
 * The samples which originate from this sample, such as through a process of cell differentiation.
 * @member {Array.<String>} origin_of
 */
Tissue.prototype['origin_of'] = undefined;

/**
 * The institutional certificates under which use of this sample is approved.
 * @member {Array.<String>} institutional_certificates
 */
Tissue.prototype['institutional_certificates'] = undefined;

/**
 * @member {module:model/Tissue.SexEnum} sex
 */
Tissue.prototype['sex'] = undefined;

/**
 * Age of organism at the time of collection of the sample.
 * @member {String} age
 */
Tissue.prototype['age'] = undefined;

/**
 * Upper bound of age of organism in hours at the time of collection of the sample.
 * @member {Number} upper_bound_age_in_hours
 */
Tissue.prototype['upper_bound_age_in_hours'] = undefined;

/**
 * Lower bound of age of organism in hours at the time of collection of the sample .
 * @member {Number} lower_bound_age_in_hours
 */
Tissue.prototype['lower_bound_age_in_hours'] = undefined;

/**
 * The parts into which this sample has been divided.
 * @member {Array.<String>} parts
 */
Tissue.prototype['parts'] = undefined;

/**
 * The pooled samples in which this sample is included.
 * @member {Array.<String>} pooled_in
 */
Tissue.prototype['pooled_in'] = undefined;

/**
 * The general category of this type of sample.
 * @member {Array.<String>} classifications
 */
Tissue.prototype['classifications'] = undefined;





/**
 * Allowed values for the <code>taxa</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['TaxaEnum'] = {

    /**
     * value: "Homo sapiens"
     * @const
     */
    "Homo sapiens": "Homo sapiens",

    /**
     * value: "Mus musculus"
     * @const
     */
    "Mus musculus": "Mus musculus"
};


/**
 * Allowed values for the <code>collections</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['CollectionsEnum'] = {

    /**
     * value: "ClinGen"
     * @const
     */
    "ClinGen": "ClinGen",

    /**
     * value: "ENCODE"
     * @const
     */
    "ENCODE": "ENCODE",

    /**
     * value: "GREGoR"
     * @const
     */
    "GREGoR": "GREGoR",

    /**
     * value: "IGVF_catalog_beta_v0.1"
     * @const
     */
    "IGVF_catalog_beta_v0.1": "IGVF_catalog_beta_v0.1",

    /**
     * value: "IGVF_catalog_beta_v0.2"
     * @const
     */
    "IGVF_catalog_beta_v0.2": "IGVF_catalog_beta_v0.2",

    /**
     * value: "IGVF_catalog_beta_v0.3"
     * @const
     */
    "IGVF_catalog_beta_v0.3": "IGVF_catalog_beta_v0.3",

    /**
     * value: "IGVF_catalog_beta_v0.4"
     * @const
     */
    "IGVF_catalog_beta_v0.4": "IGVF_catalog_beta_v0.4",

    /**
     * value: "MaveDB"
     * @const
     */
    "MaveDB": "MaveDB",

    /**
     * value: "MPRAbase"
     * @const
     */
    "MPRAbase": "MPRAbase",

    /**
     * value: "Vista"
     * @const
     */
    "Vista": "Vista"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['StatusEnum'] = {

    /**
     * value: "in progress"
     * @const
     */
    "in progress": "in progress",

    /**
     * value: "released"
     * @const
     */
    "released": "released",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "replaced"
     * @const
     */
    "replaced": "replaced",

    /**
     * value: "revoked"
     * @const
     */
    "revoked": "revoked",

    /**
     * value: "archived"
     * @const
     */
    "archived": "archived"
};


/**
 * Allowed values for the <code>age_units</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['AgeUnitsEnum'] = {

    /**
     * value: "minute"
     * @const
     */
    "minute": "minute",

    /**
     * value: "hour"
     * @const
     */
    "hour": "hour",

    /**
     * value: "day"
     * @const
     */
    "day": "day",

    /**
     * value: "week"
     * @const
     */
    "week": "week",

    /**
     * value: "month"
     * @const
     */
    "month": "month",

    /**
     * value: "year"
     * @const
     */
    "year": "year"
};


/**
 * Allowed values for the <code>starting_amount_units</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['StartingAmountUnitsEnum'] = {

    /**
     * value: "cells"
     * @const
     */
    "cells": "cells",

    /**
     * value: "cells/ml"
     * @const
     */
    "cells/ml": "cells/ml",

    /**
     * value: "g"
     * @const
     */
    "g": "g",

    /**
     * value: "items"
     * @const
     */
    "items": "items",

    /**
     * value: "mg"
     * @const
     */
    "mg": "mg",

    /**
     * value: "whole animals"
     * @const
     */
    "whole animals": "whole animals",

    /**
     * value: "whole embryos"
     * @const
     */
    "whole embryos": "whole embryos",

    /**
     * value: "μg"
     * @const
     */
    "μg": "μg",

    /**
     * value: "ng"
     * @const
     */
    "ng": "ng"
};


/**
 * Allowed values for the <code>nucleic_acid_delivery</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['NucleicAcidDeliveryEnum'] = {

    /**
     * value: "transfection"
     * @const
     */
    "transfection": "transfection",

    /**
     * value: "adenoviral transduction"
     * @const
     */
    "adenoviral transduction": "adenoviral transduction",

    /**
     * value: "lentiviral transduction"
     * @const
     */
    "lentiviral transduction": "lentiviral transduction"
};


/**
 * Allowed values for the <code>time_post_library_delivery_units</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['TimePostLibraryDeliveryUnitsEnum'] = {

    /**
     * value: "minute"
     * @const
     */
    "minute": "minute",

    /**
     * value: "hour"
     * @const
     */
    "hour": "hour",

    /**
     * value: "day"
     * @const
     */
    "day": "day",

    /**
     * value: "week"
     * @const
     */
    "week": "week",

    /**
     * value: "month"
     * @const
     */
    "month": "month"
};


/**
 * Allowed values for the <code>pmi_units</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['PmiUnitsEnum'] = {

    /**
     * value: "second"
     * @const
     */
    "second": "second",

    /**
     * value: "minute"
     * @const
     */
    "minute": "minute",

    /**
     * value: "hour"
     * @const
     */
    "hour": "hour",

    /**
     * value: "day"
     * @const
     */
    "day": "day",

    /**
     * value: "week"
     * @const
     */
    "week": "week"
};


/**
 * Allowed values for the <code>preservation_method</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['PreservationMethodEnum'] = {

    /**
     * value: "cryopreservation"
     * @const
     */
    "cryopreservation": "cryopreservation",

    /**
     * value: "flash-freezing"
     * @const
     */
    "flash-freezing": "flash-freezing"
};


/**
 * Allowed values for the <code>sex</code> property.
 * @enum {String}
 * @readonly
 */
Tissue['SexEnum'] = {

    /**
     * value: "female"
     * @const
     */
    "female": "female",

    /**
     * value: "male"
     * @const
     */
    "male": "male",

    /**
     * value: "mixed"
     * @const
     */
    "mixed": "mixed",

    /**
     * value: "unspecified"
     * @const
     */
    "unspecified": "unspecified"
};



export default Tissue;

