/* tslint:disable */
/* eslint-disable */
/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchFacet } from './SearchFacet';
import {
    SearchFacetFromJSON,
    SearchFacetFromJSONTyped,
    SearchFacetToJSON,
} from './SearchFacet';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
} from './Document';

/**
 * 
 * @export
 * @interface DocumentResults
 */
export interface DocumentResults {
    /**
     * 
     * @type {Array<Document>}
     * @memberof DocumentResults
     */
    graph?: Array<Document>;
    /**
     * 
     * @type {string}
     * @memberof DocumentResults
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DocumentResults
     */
    type?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DocumentResults
     */
    total?: number;
    /**
     * 
     * @type {Array<SearchFacet>}
     * @memberof DocumentResults
     */
    facets?: Array<SearchFacet>;
}

/**
 * Check if a given object implements the DocumentResults interface.
 */
export function instanceOfDocumentResults(value: object): value is DocumentResults {
    return true;
}

export function DocumentResultsFromJSON(json: any): DocumentResults {
    return DocumentResultsFromJSONTyped(json, false);
}

export function DocumentResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentResults {
    if (json == null) {
        return json;
    }
    return {
        
        'graph': json['@graph'] == null ? undefined : ((json['@graph'] as Array<any>).map(DocumentFromJSON)),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'total': json['total'] == null ? undefined : json['total'],
        'facets': json['facets'] == null ? undefined : ((json['facets'] as Array<any>).map(SearchFacetFromJSON)),
    };
}

export function DocumentResultsToJSON(value?: DocumentResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '@graph': value['graph'] == null ? undefined : ((value['graph'] as Array<any>).map(DocumentToJSON)),
        '@id': value['id'],
        '@type': value['type'],
        'total': value['total'],
        'facets': value['facets'] == null ? undefined : ((value['facets'] as Array<any>).map(SearchFacetToJSON)),
    };
}

