/* tslint:disable */
/* eslint-disable */
/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchFacet } from './SearchFacet';
import {
    SearchFacetFromJSON,
    SearchFacetFromJSONTyped,
    SearchFacetToJSON,
} from './SearchFacet';
import type { Gene } from './Gene';
import {
    GeneFromJSON,
    GeneFromJSONTyped,
    GeneToJSON,
} from './Gene';

/**
 * 
 * @export
 * @interface GeneResults
 */
export interface GeneResults {
    /**
     * 
     * @type {Array<Gene>}
     * @memberof GeneResults
     */
    graph?: Array<Gene>;
    /**
     * 
     * @type {string}
     * @memberof GeneResults
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneResults
     */
    type?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GeneResults
     */
    total?: number;
    /**
     * 
     * @type {Array<SearchFacet>}
     * @memberof GeneResults
     */
    facets?: Array<SearchFacet>;
}

/**
 * Check if a given object implements the GeneResults interface.
 */
export function instanceOfGeneResults(value: object): value is GeneResults {
    return true;
}

export function GeneResultsFromJSON(json: any): GeneResults {
    return GeneResultsFromJSONTyped(json, false);
}

export function GeneResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneResults {
    if (json == null) {
        return json;
    }
    return {
        
        'graph': json['@graph'] == null ? undefined : ((json['@graph'] as Array<any>).map(GeneFromJSON)),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'total': json['total'] == null ? undefined : json['total'],
        'facets': json['facets'] == null ? undefined : ((json['facets'] as Array<any>).map(SearchFacetFromJSON)),
    };
}

export function GeneResultsToJSON(value?: GeneResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '@graph': value['graph'] == null ? undefined : ((value['graph'] as Array<any>).map(GeneToJSON)),
        '@id': value['id'],
        '@type': value['type'],
        'total': value['total'],
        'facets': value['facets'] == null ? undefined : ((value['facets'] as Array<any>).map(SearchFacetToJSON)),
    };
}

