/* tslint:disable */
/* eslint-disable */
/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchFacet } from './SearchFacet';
import {
    SearchFacetFromJSON,
    SearchFacetFromJSONTyped,
    SearchFacetToJSON,
} from './SearchFacet';
import type { ModelFile } from './ModelFile';
import {
    ModelFileFromJSON,
    ModelFileFromJSONTyped,
    ModelFileToJSON,
} from './ModelFile';

/**
 * 
 * @export
 * @interface ModelFileResults
 */
export interface ModelFileResults {
    /**
     * 
     * @type {Array<ModelFile>}
     * @memberof ModelFileResults
     */
    graph?: Array<ModelFile>;
    /**
     * 
     * @type {string}
     * @memberof ModelFileResults
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelFileResults
     */
    type?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ModelFileResults
     */
    total?: number;
    /**
     * 
     * @type {Array<SearchFacet>}
     * @memberof ModelFileResults
     */
    facets?: Array<SearchFacet>;
}

/**
 * Check if a given object implements the ModelFileResults interface.
 */
export function instanceOfModelFileResults(value: object): value is ModelFileResults {
    return true;
}

export function ModelFileResultsFromJSON(json: any): ModelFileResults {
    return ModelFileResultsFromJSONTyped(json, false);
}

export function ModelFileResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelFileResults {
    if (json == null) {
        return json;
    }
    return {
        
        'graph': json['@graph'] == null ? undefined : ((json['@graph'] as Array<any>).map(ModelFileFromJSON)),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'total': json['total'] == null ? undefined : json['total'],
        'facets': json['facets'] == null ? undefined : ((json['facets'] as Array<any>).map(SearchFacetFromJSON)),
    };
}

export function ModelFileResultsToJSON(value?: ModelFileResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '@graph': value['graph'] == null ? undefined : ((value['graph'] as Array<any>).map(ModelFileToJSON)),
        '@id': value['id'],
        '@type': value['type'],
        'total': value['total'],
        'facets': value['facets'] == null ? undefined : ((value['facets'] as Array<any>).map(SearchFacetToJSON)),
    };
}

