/* tslint:disable */
/* eslint-disable */
/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoResultsResponseFacetsInnerTermsInner
 */
export interface NoResultsResponseFacetsInnerTermsInner {
    /**
     * 
     * @type {string}
     * @memberof NoResultsResponseFacetsInnerTermsInner
     */
    key?: string;
    /**
     * 
     * @type {number}
     * @memberof NoResultsResponseFacetsInnerTermsInner
     */
    docCount?: number;
}

/**
 * Check if a given object implements the NoResultsResponseFacetsInnerTermsInner interface.
 */
export function instanceOfNoResultsResponseFacetsInnerTermsInner(value: object): value is NoResultsResponseFacetsInnerTermsInner {
    return true;
}

export function NoResultsResponseFacetsInnerTermsInnerFromJSON(json: any): NoResultsResponseFacetsInnerTermsInner {
    return NoResultsResponseFacetsInnerTermsInnerFromJSONTyped(json, false);
}

export function NoResultsResponseFacetsInnerTermsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoResultsResponseFacetsInnerTermsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'docCount': json['doc_count'] == null ? undefined : json['doc_count'],
    };
}

export function NoResultsResponseFacetsInnerTermsInnerToJSON(value?: NoResultsResponseFacetsInnerTermsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'doc_count': value['docCount'],
    };
}

