/* tslint:disable */
/* eslint-disable */
/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchFacet } from './SearchFacet';
import {
    SearchFacetFromJSON,
    SearchFacetFromJSONTyped,
    SearchFacetToJSON,
} from './SearchFacet';
import type { Software } from './Software';
import {
    SoftwareFromJSON,
    SoftwareFromJSONTyped,
    SoftwareToJSON,
} from './Software';

/**
 * 
 * @export
 * @interface SoftwareResults
 */
export interface SoftwareResults {
    /**
     * 
     * @type {Array<Software>}
     * @memberof SoftwareResults
     */
    graph?: Array<Software>;
    /**
     * 
     * @type {string}
     * @memberof SoftwareResults
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SoftwareResults
     */
    type?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SoftwareResults
     */
    total?: number;
    /**
     * 
     * @type {Array<SearchFacet>}
     * @memberof SoftwareResults
     */
    facets?: Array<SearchFacet>;
}

/**
 * Check if a given object implements the SoftwareResults interface.
 */
export function instanceOfSoftwareResults(value: object): value is SoftwareResults {
    return true;
}

export function SoftwareResultsFromJSON(json: any): SoftwareResults {
    return SoftwareResultsFromJSONTyped(json, false);
}

export function SoftwareResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftwareResults {
    if (json == null) {
        return json;
    }
    return {
        
        'graph': json['@graph'] == null ? undefined : ((json['@graph'] as Array<any>).map(SoftwareFromJSON)),
        'id': json['@id'] == null ? undefined : json['@id'],
        'type': json['@type'] == null ? undefined : json['@type'],
        'total': json['total'] == null ? undefined : json['total'],
        'facets': json['facets'] == null ? undefined : ((json['facets'] as Array<any>).map(SearchFacetFromJSON)),
    };
}

export function SoftwareResultsToJSON(value?: SoftwareResults | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '@graph': value['graph'] == null ? undefined : ((value['graph'] as Array<any>).map(SoftwareToJSON)),
        '@id': value['id'],
        '@type': value['type'],
        'total': value['total'],
        'facets': value['facets'] == null ? undefined : ((value['facets'] as Array<any>).map(SearchFacetToJSON)),
    };
}

