# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictStr, field_validator
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated
from igvf_client.models.image_results import ImageResults

from igvf_client.api_client import ApiClient, RequestSerialized
from igvf_client.api_response import ApiResponse
from igvf_client.rest import RESTResponseType


class ImagesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def images(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        attachment: Annotated[Optional[Dict[str, Any]], Field(description="Filter by attachment")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        caption: Annotated[Optional[StrictStr], Field(description="Filter by caption")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        thumb_nail: Annotated[Optional[StrictStr], Field(description="Filter by thumb_nail")] = None,
        download_url: Annotated[Optional[StrictStr], Field(description="Filter by download_url")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ImageResults:
        """List items in the Image collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Image items. Supports filtering on fields within Image items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param status: Filter by status
        :type status: str
        :param attachment: Filter by attachment
        :type attachment: Attachment1
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param caption: Filter by caption
        :type caption: str
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param thumb_nail: Filter by thumb_nail
        :type thumb_nail: str
        :param download_url: Filter by download_url
        :type download_url: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._images_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            status=status,
            attachment=attachment,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            caption=caption,
            id=id,
            summary=summary,
            thumb_nail=thumb_nail,
            download_url=download_url,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ImageResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def images_with_http_info(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        attachment: Annotated[Optional[Dict[str, Any]], Field(description="Filter by attachment")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        caption: Annotated[Optional[StrictStr], Field(description="Filter by caption")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        thumb_nail: Annotated[Optional[StrictStr], Field(description="Filter by thumb_nail")] = None,
        download_url: Annotated[Optional[StrictStr], Field(description="Filter by download_url")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ImageResults]:
        """List items in the Image collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Image items. Supports filtering on fields within Image items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param status: Filter by status
        :type status: str
        :param attachment: Filter by attachment
        :type attachment: Attachment1
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param caption: Filter by caption
        :type caption: str
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param thumb_nail: Filter by thumb_nail
        :type thumb_nail: str
        :param download_url: Filter by download_url
        :type download_url: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._images_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            status=status,
            attachment=attachment,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            caption=caption,
            id=id,
            summary=summary,
            thumb_nail=thumb_nail,
            download_url=download_url,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ImageResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def images_without_preload_content(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        attachment: Annotated[Optional[Dict[str, Any]], Field(description="Filter by attachment")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        caption: Annotated[Optional[StrictStr], Field(description="Filter by caption")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        thumb_nail: Annotated[Optional[StrictStr], Field(description="Filter by thumb_nail")] = None,
        download_url: Annotated[Optional[StrictStr], Field(description="Filter by download_url")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List items in the Image collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Image items. Supports filtering on fields within Image items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param status: Filter by status
        :type status: str
        :param attachment: Filter by attachment
        :type attachment: Attachment1
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param caption: Filter by caption
        :type caption: str
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param thumb_nail: Filter by thumb_nail
        :type thumb_nail: str
        :param download_url: Filter by download_url
        :type download_url: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._images_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            status=status,
            attachment=attachment,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            caption=caption,
            id=id,
            summary=summary,
            thumb_nail=thumb_nail,
            download_url=download_url,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ImageResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _images_serialize(
        self,
        query,
        limit,
        sort,
        release_timestamp,
        status,
        attachment,
        schema_version,
        uuid,
        notes,
        aliases,
        creation_timestamp,
        submitted_by,
        submitter_comment,
        description,
        caption,
        id,
        summary,
        thumb_nail,
        download_url,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'sort': 'multi',
            'aliases': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if query is not None:
            
            _query_params.append(('query', query))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if release_timestamp is not None:
            if isinstance(release_timestamp, datetime):
                _query_params.append(
                    (
                        'release_timestamp',
                        release_timestamp.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('release_timestamp', release_timestamp))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if attachment is not None:
            
            _query_params.append(('attachment', attachment))
            
        if schema_version is not None:
            
            _query_params.append(('schema_version', schema_version))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if notes is not None:
            
            _query_params.append(('notes', notes))
            
        if aliases is not None:
            
            _query_params.append(('aliases', aliases))
            
        if creation_timestamp is not None:
            if isinstance(creation_timestamp, datetime):
                _query_params.append(
                    (
                        'creation_timestamp',
                        creation_timestamp.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('creation_timestamp', creation_timestamp))
            
        if submitted_by is not None:
            
            _query_params.append(('submitted_by', submitted_by))
            
        if submitter_comment is not None:
            
            _query_params.append(('submitter_comment', submitter_comment))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if caption is not None:
            
            _query_params.append(('caption', caption))
            
        if id is not None:
            
            _query_params.append(('@id', id))
            
        if summary is not None:
            
            _query_params.append(('summary', summary))
            
        if thumb_nail is not None:
            
            _query_params.append(('thumb_nail', thumb_nail))
            
        if download_url is not None:
            
            _query_params.append(('download_url', download_url))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter

        # Set client side default value of Query Param "frame".
        _query_params.append(('frame', 'object'))

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/images/@@listing',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


