# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, List, Optional, Union
from typing_extensions import Annotated
from igvf_client.models.treatment_results import TreatmentResults

from igvf_client.api_client import ApiClient, RequestSerialized
from igvf_client.api_response import ApiResponse
from igvf_client.rest import RESTResponseType


class TreatmentsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def treatments(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        lab: Annotated[Optional[StrictStr], Field(description="Filter by lab")] = None,
        award: Annotated[Optional[StrictStr], Field(description="Filter by award")] = None,
        sources: Annotated[Optional[List[StrictStr]], Field(description="Filter by sources")] = None,
        lot_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by lot_id")] = None,
        product_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by product_id")] = None,
        documents: Annotated[Optional[List[StrictStr]], Field(description="Filter by documents")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by amount")] = None,
        amount_units: Annotated[Optional[StrictStr], Field(description="Filter by amount_units")] = None,
        duration: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by duration")] = None,
        duration_units: Annotated[Optional[StrictStr], Field(description="Filter by duration_units")] = None,
        p_h: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by pH")] = None,
        purpose: Annotated[Optional[StrictStr], Field(description="Filter by purpose")] = None,
        post_treatment_time: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by post_treatment_time")] = None,
        post_treatment_time_units: Annotated[Optional[StrictStr], Field(description="Filter by post_treatment_time_units")] = None,
        temperature: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by temperature")] = None,
        temperature_units: Annotated[Optional[StrictStr], Field(description="Filter by temperature_units")] = None,
        treatment_type: Annotated[Optional[StrictStr], Field(description="Filter by treatment_type")] = None,
        treatment_term_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by treatment_term_id")] = None,
        treatment_term_name: Annotated[Optional[StrictStr], Field(description="Filter by treatment_term_name")] = None,
        depletion: Annotated[Optional[StrictBool], Field(description="Filter by depletion")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        biosamples_treated: Annotated[Optional[List[Any]], Field(description="Filter by biosamples_treated")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TreatmentResults:
        """List items in the Treatment collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Treatment items. Supports filtering on fields within Treatment items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param lab: Filter by lab
        :type lab: str
        :param award: Filter by award
        :type award: str
        :param sources: Filter by sources
        :type sources: List[str]
        :param lot_id: Filter by lot_id
        :type lot_id: str
        :param product_id: Filter by product_id
        :type product_id: str
        :param documents: Filter by documents
        :type documents: List[str]
        :param status: Filter by status
        :type status: str
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param amount: Filter by amount
        :type amount: float
        :param amount_units: Filter by amount_units
        :type amount_units: str
        :param duration: Filter by duration
        :type duration: float
        :param duration_units: Filter by duration_units
        :type duration_units: str
        :param p_h: Filter by pH
        :type p_h: float
        :param purpose: Filter by purpose
        :type purpose: str
        :param post_treatment_time: Filter by post_treatment_time
        :type post_treatment_time: float
        :param post_treatment_time_units: Filter by post_treatment_time_units
        :type post_treatment_time_units: str
        :param temperature: Filter by temperature
        :type temperature: float
        :param temperature_units: Filter by temperature_units
        :type temperature_units: str
        :param treatment_type: Filter by treatment_type
        :type treatment_type: str
        :param treatment_term_id: Filter by treatment_term_id
        :type treatment_term_id: str
        :param treatment_term_name: Filter by treatment_term_name
        :type treatment_term_name: str
        :param depletion: Filter by depletion
        :type depletion: bool
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param biosamples_treated: Filter by biosamples_treated
        :type biosamples_treated: List[object]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._treatments_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            lab=lab,
            award=award,
            sources=sources,
            lot_id=lot_id,
            product_id=product_id,
            documents=documents,
            status=status,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            amount=amount,
            amount_units=amount_units,
            duration=duration,
            duration_units=duration_units,
            p_h=p_h,
            purpose=purpose,
            post_treatment_time=post_treatment_time,
            post_treatment_time_units=post_treatment_time_units,
            temperature=temperature,
            temperature_units=temperature_units,
            treatment_type=treatment_type,
            treatment_term_id=treatment_term_id,
            treatment_term_name=treatment_term_name,
            depletion=depletion,
            id=id,
            summary=summary,
            biosamples_treated=biosamples_treated,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TreatmentResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def treatments_with_http_info(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        lab: Annotated[Optional[StrictStr], Field(description="Filter by lab")] = None,
        award: Annotated[Optional[StrictStr], Field(description="Filter by award")] = None,
        sources: Annotated[Optional[List[StrictStr]], Field(description="Filter by sources")] = None,
        lot_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by lot_id")] = None,
        product_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by product_id")] = None,
        documents: Annotated[Optional[List[StrictStr]], Field(description="Filter by documents")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by amount")] = None,
        amount_units: Annotated[Optional[StrictStr], Field(description="Filter by amount_units")] = None,
        duration: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by duration")] = None,
        duration_units: Annotated[Optional[StrictStr], Field(description="Filter by duration_units")] = None,
        p_h: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by pH")] = None,
        purpose: Annotated[Optional[StrictStr], Field(description="Filter by purpose")] = None,
        post_treatment_time: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by post_treatment_time")] = None,
        post_treatment_time_units: Annotated[Optional[StrictStr], Field(description="Filter by post_treatment_time_units")] = None,
        temperature: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by temperature")] = None,
        temperature_units: Annotated[Optional[StrictStr], Field(description="Filter by temperature_units")] = None,
        treatment_type: Annotated[Optional[StrictStr], Field(description="Filter by treatment_type")] = None,
        treatment_term_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by treatment_term_id")] = None,
        treatment_term_name: Annotated[Optional[StrictStr], Field(description="Filter by treatment_term_name")] = None,
        depletion: Annotated[Optional[StrictBool], Field(description="Filter by depletion")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        biosamples_treated: Annotated[Optional[List[Any]], Field(description="Filter by biosamples_treated")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TreatmentResults]:
        """List items in the Treatment collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Treatment items. Supports filtering on fields within Treatment items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param lab: Filter by lab
        :type lab: str
        :param award: Filter by award
        :type award: str
        :param sources: Filter by sources
        :type sources: List[str]
        :param lot_id: Filter by lot_id
        :type lot_id: str
        :param product_id: Filter by product_id
        :type product_id: str
        :param documents: Filter by documents
        :type documents: List[str]
        :param status: Filter by status
        :type status: str
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param amount: Filter by amount
        :type amount: float
        :param amount_units: Filter by amount_units
        :type amount_units: str
        :param duration: Filter by duration
        :type duration: float
        :param duration_units: Filter by duration_units
        :type duration_units: str
        :param p_h: Filter by pH
        :type p_h: float
        :param purpose: Filter by purpose
        :type purpose: str
        :param post_treatment_time: Filter by post_treatment_time
        :type post_treatment_time: float
        :param post_treatment_time_units: Filter by post_treatment_time_units
        :type post_treatment_time_units: str
        :param temperature: Filter by temperature
        :type temperature: float
        :param temperature_units: Filter by temperature_units
        :type temperature_units: str
        :param treatment_type: Filter by treatment_type
        :type treatment_type: str
        :param treatment_term_id: Filter by treatment_term_id
        :type treatment_term_id: str
        :param treatment_term_name: Filter by treatment_term_name
        :type treatment_term_name: str
        :param depletion: Filter by depletion
        :type depletion: bool
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param biosamples_treated: Filter by biosamples_treated
        :type biosamples_treated: List[object]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._treatments_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            lab=lab,
            award=award,
            sources=sources,
            lot_id=lot_id,
            product_id=product_id,
            documents=documents,
            status=status,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            amount=amount,
            amount_units=amount_units,
            duration=duration,
            duration_units=duration_units,
            p_h=p_h,
            purpose=purpose,
            post_treatment_time=post_treatment_time,
            post_treatment_time_units=post_treatment_time_units,
            temperature=temperature,
            temperature_units=temperature_units,
            treatment_type=treatment_type,
            treatment_term_id=treatment_term_id,
            treatment_term_name=treatment_term_name,
            depletion=depletion,
            id=id,
            summary=summary,
            biosamples_treated=biosamples_treated,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TreatmentResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def treatments_without_preload_content(
        self,
        query: Annotated[Optional[StrictStr], Field(description="Query string for searching.")] = None,
        limit: Annotated[Optional[Any], Field(description="Maximum number of results to return. Use 'all' for all results.")] = None,
        sort: Annotated[Optional[List[StrictStr]], Field(description="Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.")] = None,
        release_timestamp: Annotated[Optional[datetime], Field(description="Filter by release_timestamp")] = None,
        lab: Annotated[Optional[StrictStr], Field(description="Filter by lab")] = None,
        award: Annotated[Optional[StrictStr], Field(description="Filter by award")] = None,
        sources: Annotated[Optional[List[StrictStr]], Field(description="Filter by sources")] = None,
        lot_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by lot_id")] = None,
        product_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by product_id")] = None,
        documents: Annotated[Optional[List[StrictStr]], Field(description="Filter by documents")] = None,
        status: Annotated[Optional[StrictStr], Field(description="Filter by status")] = None,
        schema_version: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by schema_version")] = None,
        uuid: Annotated[Optional[StrictStr], Field(description="Filter by uuid")] = None,
        notes: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by notes")] = None,
        aliases: Annotated[Optional[List[Annotated[str, Field(strict=True)]]], Field(description="Filter by aliases")] = None,
        creation_timestamp: Annotated[Optional[datetime], Field(description="Filter by creation_timestamp")] = None,
        submitted_by: Annotated[Optional[StrictStr], Field(description="Filter by submitted_by")] = None,
        submitter_comment: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by submitter_comment")] = None,
        description: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by description")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by amount")] = None,
        amount_units: Annotated[Optional[StrictStr], Field(description="Filter by amount_units")] = None,
        duration: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by duration")] = None,
        duration_units: Annotated[Optional[StrictStr], Field(description="Filter by duration_units")] = None,
        p_h: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by pH")] = None,
        purpose: Annotated[Optional[StrictStr], Field(description="Filter by purpose")] = None,
        post_treatment_time: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by post_treatment_time")] = None,
        post_treatment_time_units: Annotated[Optional[StrictStr], Field(description="Filter by post_treatment_time_units")] = None,
        temperature: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Filter by temperature")] = None,
        temperature_units: Annotated[Optional[StrictStr], Field(description="Filter by temperature_units")] = None,
        treatment_type: Annotated[Optional[StrictStr], Field(description="Filter by treatment_type")] = None,
        treatment_term_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="Filter by treatment_term_id")] = None,
        treatment_term_name: Annotated[Optional[StrictStr], Field(description="Filter by treatment_term_name")] = None,
        depletion: Annotated[Optional[StrictBool], Field(description="Filter by depletion")] = None,
        id: Annotated[Optional[StrictStr], Field(description="Filter by @id")] = None,
        summary: Annotated[Optional[StrictStr], Field(description="Filter by summary")] = None,
        biosamples_treated: Annotated[Optional[List[Any]], Field(description="Filter by biosamples_treated")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List items in the Treatment collection.

        Collection endpoint that accepts various query parameters to filter, sort, and paginate Treatment items. Supports filtering on fields within Treatment items.

        :param query: Query string for searching.
        :type query: str
        :param limit: Maximum number of results to return. Use 'all' for all results.
        :type limit: SearchLimitParameter
        :param sort: Fields to sort results by. Prefix with '-' for descending order. Can be repeated for multiple sort fields. Does not work with limit=all.
        :type sort: List[str]
        :param release_timestamp: Filter by release_timestamp
        :type release_timestamp: datetime
        :param lab: Filter by lab
        :type lab: str
        :param award: Filter by award
        :type award: str
        :param sources: Filter by sources
        :type sources: List[str]
        :param lot_id: Filter by lot_id
        :type lot_id: str
        :param product_id: Filter by product_id
        :type product_id: str
        :param documents: Filter by documents
        :type documents: List[str]
        :param status: Filter by status
        :type status: str
        :param schema_version: Filter by schema_version
        :type schema_version: str
        :param uuid: Filter by uuid
        :type uuid: str
        :param notes: Filter by notes
        :type notes: str
        :param aliases: Filter by aliases
        :type aliases: List[str]
        :param creation_timestamp: Filter by creation_timestamp
        :type creation_timestamp: datetime
        :param submitted_by: Filter by submitted_by
        :type submitted_by: str
        :param submitter_comment: Filter by submitter_comment
        :type submitter_comment: str
        :param description: Filter by description
        :type description: str
        :param amount: Filter by amount
        :type amount: float
        :param amount_units: Filter by amount_units
        :type amount_units: str
        :param duration: Filter by duration
        :type duration: float
        :param duration_units: Filter by duration_units
        :type duration_units: str
        :param p_h: Filter by pH
        :type p_h: float
        :param purpose: Filter by purpose
        :type purpose: str
        :param post_treatment_time: Filter by post_treatment_time
        :type post_treatment_time: float
        :param post_treatment_time_units: Filter by post_treatment_time_units
        :type post_treatment_time_units: str
        :param temperature: Filter by temperature
        :type temperature: float
        :param temperature_units: Filter by temperature_units
        :type temperature_units: str
        :param treatment_type: Filter by treatment_type
        :type treatment_type: str
        :param treatment_term_id: Filter by treatment_term_id
        :type treatment_term_id: str
        :param treatment_term_name: Filter by treatment_term_name
        :type treatment_term_name: str
        :param depletion: Filter by depletion
        :type depletion: bool
        :param id: Filter by @id
        :type id: str
        :param summary: Filter by summary
        :type summary: str
        :param biosamples_treated: Filter by biosamples_treated
        :type biosamples_treated: List[object]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._treatments_serialize(
            query=query,
            limit=limit,
            sort=sort,
            release_timestamp=release_timestamp,
            lab=lab,
            award=award,
            sources=sources,
            lot_id=lot_id,
            product_id=product_id,
            documents=documents,
            status=status,
            schema_version=schema_version,
            uuid=uuid,
            notes=notes,
            aliases=aliases,
            creation_timestamp=creation_timestamp,
            submitted_by=submitted_by,
            submitter_comment=submitter_comment,
            description=description,
            amount=amount,
            amount_units=amount_units,
            duration=duration,
            duration_units=duration_units,
            p_h=p_h,
            purpose=purpose,
            post_treatment_time=post_treatment_time,
            post_treatment_time_units=post_treatment_time_units,
            temperature=temperature,
            temperature_units=temperature_units,
            treatment_type=treatment_type,
            treatment_term_id=treatment_term_id,
            treatment_term_name=treatment_term_name,
            depletion=depletion,
            id=id,
            summary=summary,
            biosamples_treated=biosamples_treated,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TreatmentResults",
            '400': "object",
            '404': "NoResultsResponse",
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _treatments_serialize(
        self,
        query,
        limit,
        sort,
        release_timestamp,
        lab,
        award,
        sources,
        lot_id,
        product_id,
        documents,
        status,
        schema_version,
        uuid,
        notes,
        aliases,
        creation_timestamp,
        submitted_by,
        submitter_comment,
        description,
        amount,
        amount_units,
        duration,
        duration_units,
        p_h,
        purpose,
        post_treatment_time,
        post_treatment_time_units,
        temperature,
        temperature_units,
        treatment_type,
        treatment_term_id,
        treatment_term_name,
        depletion,
        id,
        summary,
        biosamples_treated,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'sort': 'multi',
            'sources': 'multi',
            'documents': 'multi',
            'aliases': 'multi',
            'biosamples_treated': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if query is not None:
            
            _query_params.append(('query', query))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if release_timestamp is not None:
            if isinstance(release_timestamp, datetime):
                _query_params.append(
                    (
                        'release_timestamp',
                        release_timestamp.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('release_timestamp', release_timestamp))
            
        if lab is not None:
            
            _query_params.append(('lab', lab))
            
        if award is not None:
            
            _query_params.append(('award', award))
            
        if sources is not None:
            
            _query_params.append(('sources', sources))
            
        if lot_id is not None:
            
            _query_params.append(('lot_id', lot_id))
            
        if product_id is not None:
            
            _query_params.append(('product_id', product_id))
            
        if documents is not None:
            
            _query_params.append(('documents', documents))
            
        if status is not None:
            
            _query_params.append(('status', status))
            
        if schema_version is not None:
            
            _query_params.append(('schema_version', schema_version))
            
        if uuid is not None:
            
            _query_params.append(('uuid', uuid))
            
        if notes is not None:
            
            _query_params.append(('notes', notes))
            
        if aliases is not None:
            
            _query_params.append(('aliases', aliases))
            
        if creation_timestamp is not None:
            if isinstance(creation_timestamp, datetime):
                _query_params.append(
                    (
                        'creation_timestamp',
                        creation_timestamp.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('creation_timestamp', creation_timestamp))
            
        if submitted_by is not None:
            
            _query_params.append(('submitted_by', submitted_by))
            
        if submitter_comment is not None:
            
            _query_params.append(('submitter_comment', submitter_comment))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if amount is not None:
            
            _query_params.append(('amount', amount))
            
        if amount_units is not None:
            
            _query_params.append(('amount_units', amount_units))
            
        if duration is not None:
            
            _query_params.append(('duration', duration))
            
        if duration_units is not None:
            
            _query_params.append(('duration_units', duration_units))
            
        if p_h is not None:
            
            _query_params.append(('pH', p_h))
            
        if purpose is not None:
            
            _query_params.append(('purpose', purpose))
            
        if post_treatment_time is not None:
            
            _query_params.append(('post_treatment_time', post_treatment_time))
            
        if post_treatment_time_units is not None:
            
            _query_params.append(('post_treatment_time_units', post_treatment_time_units))
            
        if temperature is not None:
            
            _query_params.append(('temperature', temperature))
            
        if temperature_units is not None:
            
            _query_params.append(('temperature_units', temperature_units))
            
        if treatment_type is not None:
            
            _query_params.append(('treatment_type', treatment_type))
            
        if treatment_term_id is not None:
            
            _query_params.append(('treatment_term_id', treatment_term_id))
            
        if treatment_term_name is not None:
            
            _query_params.append(('treatment_term_name', treatment_term_name))
            
        if depletion is not None:
            
            _query_params.append(('depletion', depletion))
            
        if id is not None:
            
            _query_params.append(('@id', id))
            
        if summary is not None:
            
            _query_params.append(('summary', summary))
            
        if biosamples_treated is not None:
            
            _query_params.append(('biosamples_treated', biosamples_treated))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter

        # Set client side default value of Query Param "frame".
        _query_params.append(('frame', 'object'))

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/treatments/@@listing',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


