/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The attached content.
*/
export class Attachment {
    'download'?: string;
    'href'?: string;
    'type'?: Attachment.TypeEnum;
    'md5sum'?: string;
    'size'?: number;
    'width'?: number;
    'height'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "download",
            "baseName": "download",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Attachment.TypeEnum"
        },
        {
            "name": "md5sum",
            "baseName": "md5sum",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Attachment.attributeTypeMap;
    }
}

export namespace Attachment {
    export enum TypeEnum {
        ApplicationJson = <any> 'application/json',
        ApplicationPdf = <any> 'application/pdf',
        ImageGif = <any> 'image/gif',
        ImageJpeg = <any> 'image/jpeg',
        ImagePng = <any> 'image/png',
        ImageSvs = <any> 'image/svs',
        ImageTiff = <any> 'image/tiff',
        TextAutosql = <any> 'text/autosql',
        TextHtml = <any> 'text/html',
        TextPlain = <any> 'text/plain',
        TextTabSeparatedValues = <any> 'text/tab-separated-values'
    }
}
