/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RelatedDonor } from './relatedDonor';

/**
* A human donor of any biosample, including cell lines. Submission of any sample originating from a human donor requires submission of information about the relevant donor. For example, submission of the donor of K562 is a prerequisite for submission of any K562 cell line samples.
*/
export class HumanDonor {
    /**
    * The date the object was released.
    */
    'releaseTimestamp'?: string;
    /**
    * The species of the organism.
    */
    'taxa'?: HumanDonor.TaxaEnum;
    /**
    * The publications associated with this object.
    */
    'publications'?: Set<string>;
    /**
    * The publication identifiers that provide more information about the object.
    */
    'publicationIdentifiers'?: Set<string>;
    /**
    * An external resource with additional information.
    */
    'url'?: string;
    /**
    * Documents that provide additional information (not data file).
    */
    'documents'?: Set<string>;
    /**
    * Lab associated with the submission.
    */
    'lab'?: string;
    /**
    * Grant associated with the submission.
    */
    'award'?: string;
    /**
    * A unique identifier to be used to reference the object prefixed with IGVF.
    */
    'accession'?: string;
    /**
    * Accessions previously assigned to objects that have been merged with this object.
    */
    'alternateAccessions'?: Set<string>;
    /**
    * Some samples are part of particular data collections.
    */
    'collections'?: Set<HumanDonor.CollectionsEnum>;
    /**
    * The status of the metadata object.
    */
    'status'?: HumanDonor.StatusEnum;
    /**
    * Explanation of why an object was transitioned to the revoked status.
    */
    'revokeDetail'?: string;
    /**
    * The version of the JSON schema that the server uses to validate the object.
    */
    'schemaVersion'?: string;
    /**
    * The unique identifier associated with every object.
    */
    'uuid'?: string;
    /**
    * DACC internal notes.
    */
    'notes'?: string;
    /**
    * Lab specific identifiers to reference an object.
    */
    'aliases'?: Set<string>;
    /**
    * The date the object was created.
    */
    'creationTimestamp'?: string;
    /**
    * The user who submitted the object.
    */
    'submittedBy'?: string;
    /**
    * Additional information specified by the submitter to be displayed as a comment on the portal.
    */
    'submitterComment'?: string;
    /**
    * A plain text description of the object.
    */
    'description'?: string;
    /**
    * Identifiers from external resources that may have 1-to-1 or 1-to-many relationships with IGVF donors.
    */
    'dbxrefs'?: Set<string>;
    /**
    * Sex of the donor.
    */
    'sex'?: HumanDonor.SexEnum;
    /**
    * A list of associated phenotypic features of the donor.
    */
    'phenotypicFeatures'?: Set<string>;
    /**
    * Virtual donors are not representing actual human or model organism donors, samples coming from which were used in experiments, but rather capturing metadata about hypothetical donors that the reported analysis results are relevant for.
    */
    'virtual'?: boolean;
    /**
    * Familial relations of this donor.
    */
    'relatedDonors'?: Set<RelatedDonor>;
    /**
    * Ethnicity of the donor.
    */
    'ethnicities'?: Set<HumanDonor.EthnicitiesEnum>;
    /**
    * Identifiers of this human donor.
    */
    'humanDonorIdentifiers'?: Set<string>;
    'id'?: string;
    'type'?: Array<string>;
    /**
    * A summary of the human donor.
    */
    'summary'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "releaseTimestamp",
            "baseName": "release_timestamp",
            "type": "string"
        },
        {
            "name": "taxa",
            "baseName": "taxa",
            "type": "HumanDonor.TaxaEnum"
        },
        {
            "name": "publications",
            "baseName": "publications",
            "type": "Set<string>"
        },
        {
            "name": "publicationIdentifiers",
            "baseName": "publication_identifiers",
            "type": "Set<string>"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Set<string>"
        },
        {
            "name": "lab",
            "baseName": "lab",
            "type": "string"
        },
        {
            "name": "award",
            "baseName": "award",
            "type": "string"
        },
        {
            "name": "accession",
            "baseName": "accession",
            "type": "string"
        },
        {
            "name": "alternateAccessions",
            "baseName": "alternate_accessions",
            "type": "Set<string>"
        },
        {
            "name": "collections",
            "baseName": "collections",
            "type": "Set<HumanDonor.CollectionsEnum>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "HumanDonor.StatusEnum"
        },
        {
            "name": "revokeDetail",
            "baseName": "revoke_detail",
            "type": "string"
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "string"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string"
        },
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Set<string>"
        },
        {
            "name": "creationTimestamp",
            "baseName": "creation_timestamp",
            "type": "string"
        },
        {
            "name": "submittedBy",
            "baseName": "submitted_by",
            "type": "string"
        },
        {
            "name": "submitterComment",
            "baseName": "submitter_comment",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "dbxrefs",
            "baseName": "dbxrefs",
            "type": "Set<string>"
        },
        {
            "name": "sex",
            "baseName": "sex",
            "type": "HumanDonor.SexEnum"
        },
        {
            "name": "phenotypicFeatures",
            "baseName": "phenotypic_features",
            "type": "Set<string>"
        },
        {
            "name": "virtual",
            "baseName": "virtual",
            "type": "boolean"
        },
        {
            "name": "relatedDonors",
            "baseName": "related_donors",
            "type": "Set<RelatedDonor>"
        },
        {
            "name": "ethnicities",
            "baseName": "ethnicities",
            "type": "Set<HumanDonor.EthnicitiesEnum>"
        },
        {
            "name": "humanDonorIdentifiers",
            "baseName": "human_donor_identifiers",
            "type": "Set<string>"
        },
        {
            "name": "id",
            "baseName": "@id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "Array<string>"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HumanDonor.attributeTypeMap;
    }
}

export namespace HumanDonor {
    export enum TaxaEnum {
        HomoSapiens = <any> 'Homo sapiens'
    }
    export enum CollectionsEnum {
        ClinGen = <any> 'ClinGen',
        Encode = <any> 'ENCODE',
        GregoR = <any> 'GREGoR',
        IgvfCatalogBetaV01 = <any> 'IGVF_catalog_beta_v0.1',
        IgvfCatalogBetaV02 = <any> 'IGVF_catalog_beta_v0.2',
        IgvfCatalogBetaV03 = <any> 'IGVF_catalog_beta_v0.3',
        IgvfCatalogBetaV04 = <any> 'IGVF_catalog_beta_v0.4',
        MaveDb = <any> 'MaveDB',
        MprAbase = <any> 'MPRAbase',
        Vista = <any> 'Vista'
    }
    export enum StatusEnum {
        InProgress = <any> 'in progress',
        Released = <any> 'released',
        Deleted = <any> 'deleted',
        Replaced = <any> 'replaced',
        Revoked = <any> 'revoked',
        Archived = <any> 'archived'
    }
    export enum SexEnum {
        Male = <any> 'male',
        Female = <any> 'female',
        Unspecified = <any> 'unspecified'
    }
    export enum EthnicitiesEnum {
        AfricanAmerican = <any> 'African American',
        AfricanCaribbean = <any> 'African Caribbean',
        Arab = <any> 'Arab',
        Asian = <any> 'Asian',
        Black = <any> 'Black',
        BlackAfrican = <any> 'Black African',
        Chinese = <any> 'Chinese',
        Colombian = <any> 'Colombian',
        DaiChinese = <any> 'Dai Chinese',
        Esan = <any> 'Esan',
        Eskimo = <any> 'Eskimo',
        European = <any> 'European',
        Gambian = <any> 'Gambian',
        HanChinese = <any> 'Han Chinese',
        Hispanic = <any> 'Hispanic',
        Indian = <any> 'Indian',
        Japanese = <any> 'Japanese',
        KinhVietnamese = <any> 'Kinh Vietnamese',
        Luhya = <any> 'Luhya',
        Maasai = <any> 'Maasai',
        Mende = <any> 'Mende',
        NativeHawaiian = <any> 'Native Hawaiian',
        PacificIslander = <any> 'Pacific Islander',
        PuertoRican = <any> 'Puerto Rican',
        Yoruba = <any> 'Yoruba'
    }
}
