/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An ontology term from Cell Ontology (CL), Cell Line Ontology (CLO), Experimental Factor Ontology (EFO), or Uber-anatomy ontology (UBERON) for biological or technical samples.
*/
export class SampleTerm {
    /**
    * The date the object was released.
    */
    'releaseTimestamp'?: string;
    /**
    * The status of the metadata object.
    */
    'status'?: SampleTermStatusEnum;
    /**
    * The version of the JSON schema that the server uses to validate the object.
    */
    'schemaVersion'?: string;
    /**
    * The unique identifier associated with every object.
    */
    'uuid'?: string;
    /**
    * DACC internal notes.
    */
    'notes'?: string;
    /**
    * Lab specific identifiers to reference an object.
    */
    'aliases'?: Set<string>;
    /**
    * The date the object was created.
    */
    'creationTimestamp'?: string;
    /**
    * The user who submitted the object.
    */
    'submittedBy'?: string;
    /**
    * Additional information specified by the submitter to be displayed as a comment on the portal.
    */
    'submitterComment'?: string;
    /**
    * A plain text description of the object.
    */
    'description'?: string;
    /**
    * An ontology identifier describing a biological sample
    */
    'termId'?: string;
    /**
    * Ontology term describing a biological sample, assay, trait, or disease.
    */
    'termName'?: string;
    /**
    * A list of deprecated NTR terms previously associated with this ontology term.
    */
    'deprecatedNtrTerms'?: Set<string>;
    /**
    * A list of ontology terms which are the nearest ancestor to this ontology term.
    */
    'isA'?: Set<string>;
    /**
    * Sample identifiers from external resources, such as Cellosaurus.
    */
    'dbxrefs'?: Set<string>;
    'id'?: string;
    'type'?: Array<string>;
    /**
    * A summary of the ontology term.
    */
    'summary'?: string;
    /**
    * A unique identifier for the ontology term, reformatted from the original term ID.
    */
    'name'?: string;
    /**
    * Synonyms for the term that have been recorded in an ontology.
    */
    'synonyms'?: Set<string>;
    /**
    * List of term names of ontological terms that precede the given term in the ontological tree. These ancestor terms are typically more general ontological terms under which the term is classified.
    */
    'ancestors'?: Set<string>;
    /**
    * The ontology in which the term is recorded.
    */
    'ontology'?: string;
    /**
    * Organs associated with the sample term.
    */
    'organSlims'?: Set<string>;
    /**
    * Cells associated with the sample term.
    */
    'cellSlims'?: Set<string>;
    /**
    * Developmental stages associated with the sample term.
    */
    'developmentalSlims'?: Set<string>;
    /**
    * Organ systems associated with the sample term.
    */
    'systemSlims'?: Set<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "releaseTimestamp",
            "baseName": "release_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SampleTermStatusEnum",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "creationTimestamp",
            "baseName": "creation_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "submittedBy",
            "baseName": "submitted_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "submitterComment",
            "baseName": "submitter_comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "termId",
            "baseName": "term_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "termName",
            "baseName": "term_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "deprecatedNtrTerms",
            "baseName": "deprecated_ntr_terms",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "isA",
            "baseName": "is_a",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "dbxrefs",
            "baseName": "dbxrefs",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "synonyms",
            "baseName": "synonyms",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "ancestors",
            "baseName": "ancestors",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "ontology",
            "baseName": "ontology",
            "type": "string",
            "format": ""
        },
        {
            "name": "organSlims",
            "baseName": "organ_slims",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "cellSlims",
            "baseName": "cell_slims",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "developmentalSlims",
            "baseName": "developmental_slims",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "systemSlims",
            "baseName": "system_slims",
            "type": "Set<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SampleTerm.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SampleTermStatusEnum {
    Archived = 'archived',
    Deleted = 'deleted',
    InProgress = 'in progress',
    Released = 'released'
}

