/**
 * IGVF Project API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A user of IGVF data portal who is a member or affiliate member of IGVF.
*/
export class User {
    /**
    * The status of the metadata object.
    */
    'status'?: UserStatusEnum;
    /**
    * The version of the JSON schema that the server uses to validate the object.
    */
    'schemaVersion'?: string;
    /**
    * The unique identifier associated with every object.
    */
    'uuid'?: string;
    /**
    * DACC internal notes.
    */
    'notes'?: string;
    /**
    * Lab specific identifiers to reference an object.
    */
    'aliases'?: Set<string>;
    /**
    * The date the object was created.
    */
    'creationTimestamp'?: string;
    /**
    * The user who submitted the object.
    */
    'submittedBy'?: string;
    /**
    * Additional information specified by the submitter to be displayed as a comment on the portal.
    */
    'submitterComment'?: string;
    /**
    * A plain text description of the object.
    */
    'description'?: string;
    /**
    * The email associated with the user\'s account.
    */
    'email'?: string;
    /**
    * The user\'s first (given) name.
    */
    'firstName'?: string;
    /**
    * The user\'s last (family) name.
    */
    'lastName'?: string;
    /**
    * Lab user is primarily associated with.
    */
    'lab'?: string;
    /**
    * Labs user is authorized to submit data for.
    */
    'submitsFor'?: Set<string>;
    /**
    * Additional access control groups
    */
    'groups'?: Set<UserGroupsEnum>;
    /**
    * The group that determines which set of data the user has permission to view.
    */
    'viewingGroups'?: Set<UserViewingGroupsEnum>;
    /**
    * The role of the user in their lab or organization.
    */
    'jobTitle'?: UserJobTitleEnum;
    'id'?: string;
    'type'?: Array<string>;
    /**
    * A summary of the object.
    */
    'summary'?: string;
    /**
    * The full name of the user.
    */
    'title'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "UserStatusEnum",
            "format": ""
        },
        {
            "name": "schemaVersion",
            "baseName": "schema_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        },
        {
            "name": "aliases",
            "baseName": "aliases",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "creationTimestamp",
            "baseName": "creation_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "submittedBy",
            "baseName": "submitted_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "submitterComment",
            "baseName": "submitter_comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lab",
            "baseName": "lab",
            "type": "string",
            "format": ""
        },
        {
            "name": "submitsFor",
            "baseName": "submits_for",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Set<UserGroupsEnum>",
            "format": ""
        },
        {
            "name": "viewingGroups",
            "baseName": "viewing_groups",
            "type": "Set<UserViewingGroupsEnum>",
            "format": ""
        },
        {
            "name": "jobTitle",
            "baseName": "job_title",
            "type": "UserJobTitleEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "@id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "@type",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum UserStatusEnum {
    Current = 'current',
    Deleted = 'deleted',
    Disabled = 'disabled'
}
export enum UserGroupsEnum {
    Admin = 'admin',
    ReadOnlyAdmin = 'read-only-admin',
    Verified = 'verified'
}
export enum UserViewingGroupsEnum {
    Community = 'community',
    Igvf = 'IGVF'
}
export enum UserJobTitleEnum {
    PrincipalInvestigator = 'Principal Investigator',
    CoInvestigator = 'Co-Investigator',
    ProjectManager = 'Project Manager',
    Submitter = 'Submitter',
    PostDoc = 'Post Doc',
    DataWrangler = 'Data Wrangler',
    Scientist = 'Scientist',
    ComputationalScientist = 'Computational Scientist',
    SoftwareDeveloper = 'Software Developer',
    NhgriStaffMember = 'NHGRI staff member',
    Other = 'Other'
}

